@echo off
REM ===================================
REM   Generated by SimpleClassicTheme
REM   Version {ver}
REM 
REM   Copyright ©2020 Anis Errais
REM ===================================
goto %1


:pre
REM ===================================
REM       Programs to run before
REM       disabling classic theme
REM ===================================


goto both
:post
REM ===================================
REM        Programs to run after
REM       disabling classic theme
REM ===================================


goto both
:both
REM ===================================
REM  Programs to run before and after
REM      disabling classic theme
REM ===================================


exit