//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleClassicTheme.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleClassicTheme.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] classicStartIsBackTheme {
            get {
                object obj = ResourceManager.GetObject("classicStartIsBackTheme", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Task version=&quot;1.2&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        ///  &lt;RegistrationInfo&gt;
        ///    &lt;Date&gt;2020-08-03T20:43:25&lt;/Date&gt;
        ///    &lt;Author&gt;Anis&lt;/Author&gt;
        ///  &lt;/RegistrationInfo&gt;
        ///  &lt;Triggers&gt;
        ///    &lt;LogonTrigger&gt;
        ///      &lt;StartBoundary&gt;2020-08-03T20:43:00&lt;/StartBoundary&gt;
        ///      &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///    &lt;/LogonTrigger&gt;
        ///  &lt;/Triggers&gt;
        ///  &lt;Principals&gt;
        ///    &lt;Principal id=&quot;Author&quot;&gt;
        ///      &lt;LogonType&gt;InteractiveToken&lt;/LogonType&gt;
        ///      &lt;RunLevel&gt;HighestAva [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cmd_create_task {
            get {
                return ResourceManager.GetString("cmd_create_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] desktopControlPanelCPL {
            get {
                object obj = ResourceManager.GetObject("desktopControlPanelCPL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///REM ===================================
        ///REM   Generated by SimpleClassicTheme
        ///REM   Version {ver}
        ///REM 
        ///REM   Copyright ©2020 Anis Errais
        ///REM ===================================
        ///goto %1
        ///
        ///
        ///:pre
        ///REM ===================================
        ///REM       Programs to run before
        ///REM       disabling classic theme
        ///REM ===================================
        ///
        ///
        ///goto both
        ///:post
        ///REM ===================================
        ///REM        Programs to run after
        ///REM       disabling classic theme
        ///REM ================================== [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DisableThemeScript {
            get {
                return ResourceManager.GetString("DisableThemeScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///REM ===================================
        ///REM   Generated by SimpleClassicTheme
        ///REM   Version {ver}
        ///REM 
        ///REM   Copyright ©2020 Anis Errais
        ///REM ===================================
        ///goto %1
        ///
        ///
        ///:pre
        ///REM ===================================
        ///REM       Programs to run before
        ///REM       enabling classic theme
        ///REM ===================================
        ///
        ///
        ///goto both
        ///:post
        ///REM ===================================
        ///REM        Programs to run after
        ///REM       enabling classic theme
        ///REM ===================================
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnableThemeScript {
            get {
                return ResourceManager.GetString("EnableThemeScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ExplorerContextMenuTweaker {
            get {
                object obj = ResourceManager.GetObject("ExplorerContextMenuTweaker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fixstrips {
            get {
                object obj = ResourceManager.GetObject("fixstrips", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: SimpleClassicTheme.exe [OPERATION] {ARGS..}
        ///
        ///Operations:
        ///    /enable This enables the classic theme
        ///    /disable This disables the classic theme
        ///    /configure This opens the classic theme control panel
        ///    /boot This runs the boot circuitry of the utility. Do not use. Use /enableauto instead
        ///    /enableauto This enables/disables (depending on current state) the classic theme, and if enabled in GUI, also the taskbar.
        ///
        ///Arguments:
        ///    -t, --enable-taskbar Enables/Disables classic taskbar (Depending on  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string helpMessage {
            get {
                return ResourceManager.GetString("helpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon_application {
            get {
                object obj = ResourceManager.GetObject("icon_application", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_sct {
            get {
                object obj = ResourceManager.GetObject("logo_sct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msiexec {
            get {
                object obj = ResourceManager.GetObject("msiexec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap null_classic3small {
            get {
                object obj = ResourceManager.GetObject("null_classic3small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reg ADD &quot;HKCU\Control Panel\Appearance\Schemes&quot; /v &quot;Windows Modern&quot; /t REG_BINARY /d &quot;0200000034e439000100000010000000100000001200000012000000f5ffffff000000000000000000000000bc02000000000001000005005300650067006f0065002000550049000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f0000000f000000f5ffffff000000000000000000000000bc02000000000001000005005300650067006f0065002000550049000000000000000000000000000000000000000000000000000000000000000000000000000000000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string reg_classicschemes_add {
            get {
                return ResourceManager.GetString("reg_classicschemes_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\SOFTWARE\OpenShell\StartMenu\Settings]
        ///&quot;Version&quot;=dword:04040083
        ///&quot;MenuStyle&quot;=&quot;Classic1&quot;
        ///&quot;SkinC1&quot;=&quot;Classic Skin&quot;
        ///&quot;SkinVariationC1&quot;=&quot;&quot;
        ///&quot;SkinOptionsC1&quot;=hex(7):43,00,41,00,50,00,54,00,49,00,4f,00,4e,00,3d,00,31,00,\
        ///  00,00,55,00,53,00,45,00,52,00,5f,00,49,00,4d,00,41,00,47,00,45,00,3d,00,30,\
        ///  00,00,00,55,00,53,00,45,00,52,00,5f,00,4e,00,41,00,4d,00,45,00,3d,00,30,00,\
        ///  00,00,43,00,45,00,4e,00,54,00,45,00,52,00,5f,00,4e,00,41,00,4d,00,45,00,3d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string reg_os_settings {
            get {
                return ResourceManager.GetString("reg_os_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\SOFTWARE\OpenShell\StartMenu\Settings]
        ///&quot;MenuStyle&quot;=&quot;Classic1&quot;
        ///&quot;SkinC1&quot;=&quot;Classic Skin&quot;
        ///&quot;SkinVariationC1&quot;=&quot;&quot;
        ///&quot;SkinOptionsC1&quot;=hex(7):43,00,41,00,50,00,54,00,49,00,4f,00,4e,00,3d,00,31,00,\
        ///  00,00,55,00,53,00,45,00,52,00,5f,00,49,00,4d,00,41,00,47,00,45,00,3d,00,30,\
        ///  00,00,00,55,00,53,00,45,00,52,00,5f,00,4e,00,41,00,4d,00,45,00,3d,00,30,00,\
        ///  00,00,43,00,45,00,4e,00,54,00,45,00,52,00,5f,00,4e,00,41,00,4d,00,45,00,3d,\
        ///  00,30,00,00,00,53,00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string reg_os_sm_settings {
            get {
                return ResourceManager.GetString("reg_os_sm_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\SOFTWARE\OpenShell\StartMenu\Settings]
        ///&quot;EnableStartButton&quot;=dword:00000001
        ///&quot;StartButtonType&quot;=&quot;CustomButton&quot;
        ///&quot;StartButtonPath&quot;=&quot;%USERPROFILE%\\AppData\\Local\\StartIsBack\\Orbs\\CS_classic3small.bmp&quot;
        ///&quot;CustomTaskbar&quot;=dword:00000001
        ///&quot;TaskbarLook&quot;=&quot;Opaque&quot;
        ///&quot;TaskbarTexture&quot;=&quot;%USERPROFILE%\\AppData\\Local\\StartIsBack\\Orbs\\taskbar.png&quot;
        ///.
        /// </summary>
        internal static string reg_os_tb_settings {
            get {
                return ResourceManager.GetString("reg_os_tb_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\SOFTWARE\StartIsBack]
        ///&quot;WelcomeShown&quot;=dword:00000002
        ///&quot;ModernIconsColorized&quot;=dword:00000002
        ///&quot;Start_LargeMFUIcons&quot;=dword:00000001
        ///&quot;StartMetroAppsMFU&quot;=dword:00000001
        ///&quot;StartScreenShortcut&quot;=dword:00000000
        ///&quot;Start_SortByName&quot;=dword:00000001
        ///&quot;StartMetroAppsFolder&quot;=dword:00000001
        ///&quot;Start_SortFoldersFirst&quot;=dword:00000000
        ///&quot;Start_NotifyNewApps&quot;=dword:00000001
        ///&quot;Start_AutoCascade&quot;=dword:00000001
        ///&quot;Start_AskCortana&quot;=dword:00000000
        ///&quot;Start_RightPaneIcons&quot;=d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string reg_sib_settings {
            get {
                return ResourceManager.GetString("reg_sib_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Control Panel\Desktop]
        ///&quot;UserPreferencesMask&quot;=hex:9e,3e,07,80,12,00,00,00.
        /// </summary>
        internal static string reg_upm_disable3d {
            get {
                return ResourceManager.GetString("reg_upm_disable3d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Control Panel\Desktop]
        ///&quot;UserPreferencesMask&quot;=hex:be,1e,05,80,12,00,00,00.
        /// </summary>
        internal static string reg_upm_enable3d {
            get {
                return ResourceManager.GetString("reg_upm_enable3d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Control Panel\Appearance]
        ///&quot;CustomColors&quot;=hex:3a,6e,a5,00,ff,ff,ff,00,ff,ff,ff,00,ff,ff,ff,00,ff,ff,ff,00,\
        ///  ff,ff,ff,00,ff,ff,ff,00,ff,ff,ff,00,ff,ff,ff,00,ff,ff,ff,00,ff,ff,ff,00,ff,\
        ///  ff,ff,00,ff,ff,ff,00,ff,ff,ff,00,ff,ff,ff,00,ff,ff,ff,00
        ///&quot;Current&quot;=&quot;Windows Aero&quot;
        ///.
        /// </summary>
        internal static string reg_windowcolors_restore {
            get {
                return ResourceManager.GetString("reg_windowcolors_restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics]
        ///&quot;BorderWidth&quot;=&quot;-15&quot;
        ///&quot;ScrollWidth&quot;=&quot;-255&quot;
        ///&quot;ScrollHeight&quot;=&quot;-255&quot;
        ///&quot;CaptionWidth&quot;=&quot;-330&quot;
        ///&quot;CaptionHeight&quot;=&quot;-330&quot;
        ///&quot;SmCaptionWidth&quot;=&quot;-330&quot;
        ///&quot;SmCaptionHeight&quot;=&quot;-330&quot;
        ///&quot;MenuWidth&quot;=&quot;-285&quot;
        ///&quot;MenuHeight&quot;=&quot;-285&quot;
        ///&quot;CaptionFont&quot;=hex:f1,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,00,\
        ///  00,00,00,01,00,00,05,00,53,00,65,00,67,00,6f,00,65,00,20,00,55,00,49,00,00,\
        ///  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string reg_windowmetrics_81 {
            get {
                return ResourceManager.GetString("reg_windowmetrics_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics]
        ///
        ///&quot;CaptionHeight&quot;=&quot;-330&quot;
        ///&quot;CaptionWidth&quot;=&quot;-330&quot;
        ///&quot;CaptionFont&quot;=hex:f4,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,00,\
        ///  00,00,00,01,00,00,05,00,53,00,65,00,67,00,6f,00,65,00,20,00,55,00,49,00,00,\
        ///  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
        ///  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
        ///&quot;ScrollWidth&quot;=&quot;-255&quot;
        ///&quot;ScrollHeight&quot;=&quot;-255&quot;
        ///&quot;PaddedBorderWidth&quot;=&quot;-6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string reg_windowmetrics_restore {
            get {
                return ResourceManager.GetString("reg_windowmetrics_restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///title SCT Uninstallation
        ///echo Removing final SCT files
        ///timeout 5 &gt; nul
        ///rmdir /S /Q C:\SCT
        ///shutdown.exe -r -t 2
        ///(goto) 2&gt;nul &amp; del &quot;%~f0&quot;.
        /// </summary>
        internal static string removalString {
            get {
                return ResourceManager.GetString("removalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ribbonDisabler {
            get {
                object obj = ResourceManager.GetObject("ribbonDisabler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_classic_taskmgr {
            get {
                object obj = ResourceManager.GetObject("setup_classic-taskmgr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_folder_options_x {
            get {
                object obj = ResourceManager.GetObject("setup_folder-options-x", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_open_shell {
            get {
                object obj = ResourceManager.GetObject("setup_open-shell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ShellPayload {
            get {
                object obj = ResourceManager.GetObject("ShellPayload", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap taskbar {
            get {
                object obj = ResourceManager.GetObject("taskbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks /Delete /TN &quot;Simple Classic Theme&quot; /F
        ///schtasks /Create /TN &quot;Simple Classic Theme&quot; /XML &quot;C:\SCT\SCTTask.xml&quot;.
        /// </summary>
        internal static string taskScheduleCommands {
            get {
                return ResourceManager.GetString("taskScheduleCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///title Installing SimpleClassicTheme v%1 
        ///echo Installing...
        ///timeout 5 &gt; nul
        ///taskkill /im %2 /f &gt; nul 2&gt;&amp;1
        ///del %2 &gt; nul
        ///copy %3 %2 &gt; nul
        ///del %3 &gt; nul
        ///%2
        ///(goto) 2&gt;nul &amp; del &quot;%~f0&quot;.
        /// </summary>
        internal static string updateString {
            get {
                return ResourceManager.GetString("updateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap win7 {
            get {
                object obj = ResourceManager.GetObject("win7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap win98sct {
            get {
                object obj = ResourceManager.GetObject("win98sct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap win9x {
            get {
                object obj = ResourceManager.GetObject("win9x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap winxp_wizard {
            get {
                object obj = ResourceManager.GetObject("winxp_wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
