//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleClassicTheme.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleClassicTheme.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reg ADD &quot;HKCU\Control Panel\Appearance\Schemes&quot; /v &quot;Windows Modern&quot; /t REG_BINARY /d &quot;0200000034e439000100000010000000100000001200000012000000f5ffffff000000000000000000000000bc02000000000001000005005300650067006f0065002000550049000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f0000000f000000f5ffffff000000000000000000000000bc02000000000001000005005300650067006f0065002000550049000000000000000000000000000000000000000000000000000000000000000000000000000000000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string addSchemes {
            get {
                return ResourceManager.GetString("addSchemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] classicStartIsBackTheme {
            get {
                object obj = ResourceManager.GetObject("classicStartIsBackTheme", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] classicTaskManager {
            get {
                object obj = ResourceManager.GetObject("classicTaskManager", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] desktopControlPanelCPL {
            get {
                object obj = ResourceManager.GetObject("desktopControlPanelCPL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ExplorerContextMenuTweaker {
            get {
                object obj = ResourceManager.GetObject("ExplorerContextMenuTweaker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fixstrips {
            get {
                object obj = ResourceManager.GetObject("fixstrips", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] folderOptionsX {
            get {
                object obj = ResourceManager.GetObject("folderOptionsX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: SimpleClassicTheme.exe [OPERATION] {ARGS..}
        ///
        ///Operations:
        ///    /enable This enables the classic theme
        ///    /disable This disables the classic theme
        ///    /configure This opens the classic theme control panel
        ///    /boot This runs the boot circuitry of the utility. Do not use. Use /enableauto instead
        ///    /enableauto This enables/disables (depending on current state) the classic theme, and if enabled in GUI, also the taskbar.
        ///
        ///Arguments:
        ///    -t, --enable-taskbar Enables/Disables classic taskbar (Dep [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string helpMessage {
            get {
                return ResourceManager.GetString("helpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap null_classic3small {
            get {
                object obj = ResourceManager.GetObject("null_classic3small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\SOFTWARE\OpenShell\StartMenu\Settings]
        ///&quot;Version&quot;=dword:04040083
        ///&quot;MenuStyle&quot;=&quot;Classic1&quot;
        ///&quot;SkinC1&quot;=&quot;Classic Skin&quot;
        ///&quot;SkinVariationC1&quot;=&quot;&quot;
        ///&quot;SkinOptionsC1&quot;=hex(7):43,00,41,00,50,00,54,00,49,00,4f,00,4e,00,3d,00,31,00,\
        ///  00,00,55,00,53,00,45,00,52,00,5f,00,49,00,4d,00,41,00,47,00,45,00,3d,00,30,\
        ///  00,00,00,55,00,53,00,45,00,52,00,5f,00,4e,00,41,00,4d,00,45,00,3d,00,30,00,\
        ///  00,00,43,00,45,00,4e,00,54,00,45,00,52,00,5f,00,4e,00,41,00,4d,00,45,00,3d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string openShellSettings {
            get {
                return ResourceManager.GetString("openShellSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] openShellSetup {
            get {
                object obj = ResourceManager.GetObject("openShellSetup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics]
        ///
        ///&quot;CaptionHeight&quot;=&quot;-330&quot;
        ///&quot;CaptionWidth&quot;=&quot;-330&quot;
        ///&quot;CaptionFont&quot;=hex:f4,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,00,\
        ///  00,00,00,01,00,00,05,00,53,00,65,00,67,00,6f,00,65,00,20,00,55,00,49,00,00,\
        ///  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
        ///  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
        ///&quot;ScrollWidth&quot;=&quot;-255&quot;
        ///&quot;ScrollHeight&quot;=&quot;-255&quot;
        ///&quot;PaddedBord [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string restoreWindowMetrics {
            get {
                return ResourceManager.GetString("restoreWindowMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ribbonDisabler {
            get {
                object obj = ResourceManager.GetObject("ribbonDisabler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Task version=&quot;1.2&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        ///  &lt;RegistrationInfo&gt;
        ///    &lt;Date&gt;2020-08-03T20:43:25&lt;/Date&gt;
        ///    &lt;Author&gt;Anis&lt;/Author&gt;
        ///  &lt;/RegistrationInfo&gt;
        ///  &lt;Triggers&gt;
        ///    &lt;LogonTrigger&gt;
        ///      &lt;StartBoundary&gt;2020-08-03T20:43:00&lt;/StartBoundary&gt;
        ///      &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///    &lt;/LogonTrigger&gt;
        ///  &lt;/Triggers&gt;
        ///  &lt;Principals&gt;
        ///    &lt;Principal id=&quot;Author&quot;&gt;
        ///      &lt;LogonType&gt;InteractiveToken&lt;/LogonType&gt;
        ///      &lt;RunLevel&gt;HighestAva [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string scttask {
            get {
                return ResourceManager.GetString("scttask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ShellPayload {
            get {
                object obj = ResourceManager.GetObject("ShellPayload", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\SOFTWARE\StartIsBack]
        ///&quot;WelcomeShown&quot;=dword:00000002
        ///&quot;ModernIconsColorized&quot;=dword:00000002
        ///&quot;Start_LargeMFUIcons&quot;=dword:00000001
        ///&quot;StartMetroAppsMFU&quot;=dword:00000001
        ///&quot;StartScreenShortcut&quot;=dword:00000000
        ///&quot;Start_SortByName&quot;=dword:00000001
        ///&quot;StartMetroAppsFolder&quot;=dword:00000001
        ///&quot;Start_SortFoldersFirst&quot;=dword:00000000
        ///&quot;Start_NotifyNewApps&quot;=dword:00000001
        ///&quot;Start_AutoCascade&quot;=dword:00000001
        ///&quot;Start_AskCortana&quot;=dword:00000000
        ///&quot;Start_RightPaneIcons&quot;=d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string startIsBackSettings {
            get {
                return ResourceManager.GetString("startIsBackSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap taskbar {
            get {
                object obj = ResourceManager.GetObject("taskbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks /Delete /TN &quot;Simple Classic Theme&quot; /F
        ///schtasks /Create /TN &quot;Simple Classic Theme&quot; /XML &quot;C:\SCT\SCTTask.xml&quot;.
        /// </summary>
        internal static string taskScheduleCommands {
            get {
                return ResourceManager.GetString("taskScheduleCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///title Installing SimpleClassicTheme v%1 
        ///echo Installing...
        ///timeout 5 &gt; nul
        ///taskkill /im %2 /f &gt; nul 2&gt;&amp;1
        ///del %2 &gt; nul
        ///copy %3 %2 &gt; nul
        ///del %3 &gt; nul
        ///%2
        ///(goto) 2&gt;nul &amp; del &quot;%~f0&quot;.
        /// </summary>
        internal static string updateString {
            get {
                return ResourceManager.GetString("updateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Control Panel\Desktop]
        ///&quot;UserPreferencesMask&quot;=hex:be,1e,05,80,12,00,00,00.
        /// </summary>
        internal static string upmReg {
            get {
                return ResourceManager.GetString("upmReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap win7 {
            get {
                object obj = ResourceManager.GetObject("win7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap win98sct {
            get {
                object obj = ResourceManager.GetObject("win98sct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap win98sctbanner {
            get {
                object obj = ResourceManager.GetObject("win98sctbanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap win9x {
            get {
                object obj = ResourceManager.GetObject("win9x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics]
        ///&quot;CaptionFont&quot;=hex:f5,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,bc,02,00,00,\
        ///  00,00,00,00,00,00,00,00,54,00,61,00,68,00,6f,00,6d,00,61,00,00,00,00,00,00,\
        ///  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
        ///  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
        ///&quot;IconFont&quot;=hex:f5,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,00,00,\
        ///  00,00,00,00,00,00,00,5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WindowMetrics {
            get {
                return ResourceManager.GetString("WindowMetrics", resourceCulture);
            }
        }
    }
}
